-- Little Moon Stories - Supabase Subscription & Children Table Schema
-- Instructions: Copy-paste this SQL block into your Supabase Dashboard's "SQL Editor" to create the required tables instantly.

CREATE TABLE IF NOT EXISTS public.subscribers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  parent_email TEXT NOT NULL,
  age_range TEXT NOT NULL DEFAULT '3-5',
  delivery_time TIME NOT NULL DEFAULT '20:00',
  timezone TEXT NOT NULL DEFAULT 'America/New_York',
  preferred_theme TEXT NOT NULL DEFAULT 'Adventure',
  favorite_hobby TEXT NOT NULL DEFAULT 'reading',
  favorite_animal TEXT NOT NULL DEFAULT 'elephant',
  plan_type TEXT NOT NULL DEFAULT 'monthly',
  payment_status INTEGER NOT NULL DEFAULT 0, -- 0 for unpaid, 1 for paid
  package_end_date TIMESTAMP WITH TIME ZONE, -- End date of monthly package
  payment_provider_order_id TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE IF NOT EXISTS public.children (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  subscriber_id BIGINT REFERENCES public.subscribers(id) ON DELETE CASCADE,
  nickname TEXT NOT NULL,
  gender TEXT NOT NULL,
  birthday TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE IF NOT EXISTS public.story_jobs (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  subscriber_id BIGINT NOT NULL REFERENCES public.subscribers(id) ON DELETE CASCADE,
  story_date DATE NOT NULL,
  scheduled_generation_at TIMESTAMP WITH TIME ZONE NOT NULL,
  scheduled_delivery_at TIMESTAMP WITH TIME ZONE NOT NULL,
  status TEXT NOT NULL DEFAULT 'pending_generation',
  prompt_payload JSONB NOT NULL DEFAULT '{}'::jsonb,
  story_text TEXT,
  error_message TEXT,
  generation_attempts INTEGER NOT NULL DEFAULT 0,
  last_generation_failed_at TIMESTAMP WITH TIME ZONE,
  generated_at TIMESTAMP WITH TIME ZONE,
  sent_at TIMESTAMP WITH TIME ZONE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  UNIQUE (subscriber_id, story_date)
);

CREATE TABLE IF NOT EXISTS public.story_audio (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  story_job_id UUID NOT NULL REFERENCES public.story_jobs(id) ON DELETE CASCADE,
  storage_bucket TEXT NOT NULL DEFAULT 'story-audio',
  storage_path TEXT NOT NULL,
  mime_type TEXT NOT NULL DEFAULT 'audio/mpeg',
  file_size_bytes BIGINT,
  duration_seconds INTEGER,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  UNIQUE (story_job_id)
);

CREATE TABLE IF NOT EXISTS public.delivery_attempts (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  story_job_id UUID NOT NULL REFERENCES public.story_jobs(id) ON DELETE CASCADE,
  parent_email TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'pending',
  provider_message_id TEXT,
  error_message TEXT,
  attempted_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES (
  'story-audio',
  'story-audio',
  false,
  52428800,
  ARRAY['audio/mpeg', 'audio/mp3', 'audio/wav', 'audio/x-wav']
)
ON CONFLICT (id) DO UPDATE SET
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

-- Run-safe migration for existing projects created before timezone was split out
ALTER TABLE public.subscribers
  ADD COLUMN IF NOT EXISTS timezone TEXT NOT NULL DEFAULT 'America/New_York';

-- Drop old helper view if it exists, because it can block changing delivery_time to TIME.
-- Recreate this view later only if you still need it for manual reporting.
DROP VIEW IF EXISTS public.subscriber_family_view;

ALTER TABLE public.subscribers
  ALTER COLUMN delivery_time DROP DEFAULT;

ALTER TABLE public.subscribers
  ALTER COLUMN delivery_time TYPE TIME
  USING split_part(delivery_time::text, ' ', 1)::time;

ALTER TABLE public.subscribers
  ALTER COLUMN delivery_time SET DEFAULT '20:00';

DO $$
BEGIN
  IF EXISTS (
    SELECT 1
    FROM information_schema.columns
    WHERE table_schema = 'public'
      AND table_name = 'subscribers'
      AND column_name = 'stripe_checkout_session_id'
  ) AND NOT EXISTS (
    SELECT 1
    FROM information_schema.columns
    WHERE table_schema = 'public'
      AND table_name = 'subscribers'
      AND column_name = 'payment_provider_order_id'
  ) THEN
    ALTER TABLE public.subscribers
      RENAME COLUMN stripe_checkout_session_id TO payment_provider_order_id;
  END IF;
END $$;

ALTER TABLE public.subscribers
  ADD COLUMN IF NOT EXISTS payment_provider_order_id TEXT;

ALTER TABLE public.subscribers
  DROP COLUMN IF EXISTS expires_at;

ALTER TABLE public.story_jobs
  ADD COLUMN IF NOT EXISTS generation_attempts INTEGER NOT NULL DEFAULT 0;

ALTER TABLE public.story_jobs
  ADD COLUMN IF NOT EXISTS last_generation_failed_at TIMESTAMP WITH TIME ZONE;

CREATE INDEX IF NOT EXISTS idx_subscribers_paid_package
  ON public.subscribers(payment_status, package_end_date);

-- A parent email can receive only one free story, even if requests arrive concurrently.
CREATE UNIQUE INDEX IF NOT EXISTS idx_subscribers_one_free_trial_per_email
  ON public.subscribers(lower(btrim(parent_email)))
  WHERE plan_type = 'free_trial';

CREATE INDEX IF NOT EXISTS idx_children_subscriber_id
  ON public.children(subscriber_id);

CREATE INDEX IF NOT EXISTS idx_story_jobs_generation_queue
  ON public.story_jobs(status, scheduled_generation_at);

CREATE INDEX IF NOT EXISTS idx_story_jobs_delivery_queue
  ON public.story_jobs(status, scheduled_delivery_at);

CREATE INDEX IF NOT EXISTS idx_story_audio_job_id
  ON public.story_audio(story_job_id);

CREATE OR REPLACE FUNCTION public.enqueue_tomorrow_story_jobs()
RETURNS INTEGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  inserted_count INTEGER;
BEGIN
  INSERT INTO public.story_jobs (
    subscriber_id,
    story_date,
    scheduled_generation_at,
    scheduled_delivery_at,
    prompt_payload
  )
  SELECT
    s.id,
    job.story_date,
    job.scheduled_delivery_at - interval '1 day',
    job.scheduled_delivery_at,
    jsonb_build_object(
      'parent_email', s.parent_email,
      'age_range', s.age_range,
      'preferred_theme', s.preferred_theme,
      'favorite_hobby', s.favorite_hobby,
      'favorite_animal', s.favorite_animal,
      'timezone', s.timezone,
      'delivery_time', s.delivery_time,
      'children', coalesce(
        jsonb_agg(
          jsonb_build_object(
            'nickname', c.nickname,
            'gender', c.gender,
            'birthday', c.birthday
          )
          ORDER BY c.id
        ) filter (where c.id is not null),
        '[]'::jsonb
      )
    )
  FROM public.subscribers s
  CROSS JOIN LATERAL (
    SELECT
      ((now() AT TIME ZONE s.timezone)::date + interval '1 day')::date AS story_date,
      (
        (((now() AT TIME ZONE s.timezone)::date + interval '1 day')::date + s.delivery_time)
        AT TIME ZONE s.timezone
      ) AS scheduled_delivery_at
  ) job
  LEFT JOIN public.children c ON c.subscriber_id = s.id
  WHERE s.payment_status = 1
    AND s.package_end_date >= job.scheduled_delivery_at
  GROUP BY s.id, job.story_date, job.scheduled_delivery_at
  ON CONFLICT (subscriber_id, story_date) DO NOTHING;

  GET DIAGNOSTICS inserted_count = ROW_COUNT;
  RETURN inserted_count;
END;
$$;

CREATE OR REPLACE FUNCTION public.enqueue_signup_story_job(
  p_subscriber_id BIGINT,
  p_minimum_lead_time INTERVAL DEFAULT interval '5 hours'
)
RETURNS UUID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  inserted_story_job_id UUID;
BEGIN
  INSERT INTO public.story_jobs (
    subscriber_id,
    story_date,
    scheduled_generation_at,
    scheduled_delivery_at,
    prompt_payload
  )
  SELECT
    s.id,
    job.story_date,
    now(),
    job.scheduled_delivery_at,
    jsonb_build_object(
      'parent_email', s.parent_email,
      'age_range', s.age_range,
      'preferred_theme', s.preferred_theme,
      'favorite_hobby', s.favorite_hobby,
      'favorite_animal', s.favorite_animal,
      'timezone', s.timezone,
      'delivery_time', s.delivery_time,
      'children', coalesce(
        jsonb_agg(
          jsonb_build_object(
            'nickname', c.nickname,
            'gender', c.gender,
            'birthday', c.birthday
          )
          ORDER BY c.id
        ) filter (where c.id is not null),
        '[]'::jsonb
      )
    )
  FROM public.subscribers s
  CROSS JOIN LATERAL (
    SELECT
      (now() AT TIME ZONE s.timezone)::date AS story_date,
      (
        ((now() AT TIME ZONE s.timezone)::date + s.delivery_time)
        AT TIME ZONE s.timezone
      ) AS scheduled_delivery_at
  ) job
  LEFT JOIN public.children c ON c.subscriber_id = s.id
  WHERE s.id = p_subscriber_id
    AND s.payment_status = 1
    AND job.scheduled_delivery_at >= now() + p_minimum_lead_time
    AND s.package_end_date >= job.scheduled_delivery_at
  GROUP BY s.id, job.story_date, job.scheduled_delivery_at
  ON CONFLICT (subscriber_id, story_date) DO NOTHING
  RETURNING id INTO inserted_story_job_id;

  RETURN inserted_story_job_id;
END;
$$;

CREATE OR REPLACE FUNCTION public.enqueue_signup_story_job_with_message(
  p_subscriber_id BIGINT,
  p_minimum_lead_time INTERVAL DEFAULT interval '5 hours'
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  subscriber_record public.subscribers%ROWTYPE;
  child_count INTEGER;
  local_story_date DATE;
  scheduled_delivery_at TIMESTAMP WITH TIME ZONE;
  existing_story_job_id UUID;
  inserted_story_job_id UUID;
BEGIN
  SELECT *
    INTO subscriber_record
  FROM public.subscribers
  WHERE id = p_subscriber_id;

  IF NOT FOUND THEN
    RETURN jsonb_build_object(
      'ok', false,
      'code', 'subscriber_not_found',
      'message', 'No subscriber was found for this id.'
    );
  END IF;

  IF subscriber_record.payment_status <> 1 THEN
    RETURN jsonb_build_object(
      'ok', false,
      'code', 'not_paid',
      'message', 'This parent is registered but not paid yet, so no same-day story job can be created.'
    );
  END IF;

  SELECT count(*)
    INTO child_count
  FROM public.children
  WHERE subscriber_id = p_subscriber_id;

  IF child_count = 0 THEN
    RETURN jsonb_build_object(
      'ok', false,
      'code', 'missing_children',
      'message', 'This subscriber has no child profile, so the story prompt would be incomplete.'
    );
  END IF;

  local_story_date := (now() AT TIME ZONE subscriber_record.timezone)::date;
  scheduled_delivery_at := (
    (local_story_date + subscriber_record.delivery_time)
    AT TIME ZONE subscriber_record.timezone
  );

  SELECT id
    INTO existing_story_job_id
  FROM public.story_jobs
  WHERE subscriber_id = p_subscriber_id
    AND story_date = local_story_date
  LIMIT 1;

  IF existing_story_job_id IS NOT NULL THEN
    RETURN jsonb_build_object(
      'ok', true,
      'code', 'already_exists',
      'story_job_id', existing_story_job_id,
      'message', 'A same-day story job already exists for this parent.'
    );
  END IF;

  IF scheduled_delivery_at < now() + p_minimum_lead_time THEN
    RETURN jsonb_build_object(
      'ok', false,
      'code', 'not_enough_lead_time',
      'message', format(
        'Same-day delivery was not created because the selected delivery time is less than %s away.',
        p_minimum_lead_time
      ),
      'scheduled_delivery_at', scheduled_delivery_at
    );
  END IF;

  IF subscriber_record.package_end_date IS NULL
     OR subscriber_record.package_end_date < scheduled_delivery_at THEN
    RETURN jsonb_build_object(
      'ok', false,
      'code', 'package_not_active_for_delivery',
      'message', 'The monthly package does not cover the selected same-day delivery time.',
      'scheduled_delivery_at', scheduled_delivery_at,
      'package_end_date', subscriber_record.package_end_date
    );
  END IF;

  inserted_story_job_id := public.enqueue_signup_story_job(
    p_subscriber_id,
    p_minimum_lead_time
  );

  IF inserted_story_job_id IS NULL THEN
    RETURN jsonb_build_object(
      'ok', false,
      'code', 'not_created',
      'message', 'No story job was created. Please check payment status, package date, delivery time, and duplicate jobs.'
    );
  END IF;

  RETURN jsonb_build_object(
    'ok', true,
    'code', 'created',
    'story_job_id', inserted_story_job_id,
    'message', 'Same-day story job created successfully.',
    'scheduled_delivery_at', scheduled_delivery_at
  );
END;
$$;

DROP FUNCTION IF EXISTS public.get_ready_story_deliveries(INTEGER);

CREATE OR REPLACE FUNCTION public.claim_ready_story_generations(batch_size INTEGER DEFAULT 5)
RETURNS TABLE (
  id UUID,
  subscriber_id BIGINT,
  story_date DATE,
  scheduled_generation_at TIMESTAMP WITH TIME ZONE,
  scheduled_delivery_at TIMESTAMP WITH TIME ZONE,
  prompt_payload JSONB
)
LANGUAGE sql
SECURITY DEFINER
SET search_path = public
AS $$
  WITH picked AS (
    SELECT j.id
    FROM public.story_jobs j
    JOIN public.subscribers s ON s.id = j.subscriber_id
    WHERE j.status = 'pending_generation'
      AND j.scheduled_generation_at <= now()
      AND s.payment_status = 1
      AND s.package_end_date >= j.scheduled_delivery_at
    ORDER BY j.scheduled_generation_at ASC
    LIMIT batch_size
    FOR UPDATE OF j SKIP LOCKED
  ),
  updated AS (
    UPDATE public.story_jobs j
    SET
      status = 'generating',
      updated_at = now(),
      error_message = NULL,
      generation_attempts = j.generation_attempts + 1
    FROM picked p
    WHERE j.id = p.id
    RETURNING j.*
  )
  SELECT
    u.id,
    u.subscriber_id,
    u.story_date,
    u.scheduled_generation_at,
    u.scheduled_delivery_at,
    u.prompt_payload
  FROM updated u;
$$;

CREATE OR REPLACE FUNCTION public.mark_story_generation_failed(
  p_story_job_id UUID,
  p_error_message TEXT,
  p_retry BOOLEAN DEFAULT true
)
RETURNS VOID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  UPDATE public.story_jobs
  SET
    status = CASE
      WHEN p_retry = true AND generation_attempts < 3 THEN 'pending_generation'
      ELSE 'generation_failed'
    END,
    scheduled_generation_at = CASE
      WHEN p_retry = true AND generation_attempts < 3 THEN now() + interval '10 minutes'
      ELSE scheduled_generation_at
    END,
    updated_at = now(),
    last_generation_failed_at = now(),
    error_message = p_error_message
  WHERE id = p_story_job_id;
END;
$$;

CREATE OR REPLACE FUNCTION public.claim_ready_story_deliveries(batch_size INTEGER DEFAULT 100)
RETURNS TABLE (
  story_job_id UUID,
  subscriber_id BIGINT,
  parent_email TEXT,
  story_date DATE,
  scheduled_delivery_at TIMESTAMP WITH TIME ZONE,
  storage_bucket TEXT,
  storage_path TEXT,
  mime_type TEXT,
  story_text TEXT
)
LANGUAGE sql
SECURITY DEFINER
SET search_path = public
AS $$
  WITH picked AS (
    SELECT j.id
    FROM public.story_jobs j
    JOIN public.subscribers s ON s.id = j.subscriber_id
    JOIN public.story_audio a ON a.story_job_id = j.id
    WHERE j.status = 'ready_to_send'
      AND j.scheduled_delivery_at <= now() + interval '5 minutes'
      AND s.payment_status = 1
      AND s.package_end_date >= now()
    ORDER BY j.scheduled_delivery_at ASC
    LIMIT batch_size
    FOR UPDATE OF j SKIP LOCKED
  ),
  updated AS (
    UPDATE public.story_jobs j
    SET
      status = 'sending',
      updated_at = now()
    FROM picked p
    WHERE j.id = p.id
    RETURNING j.*
  )
  SELECT
    u.id,
    u.subscriber_id,
    s.parent_email,
    u.story_date,
    u.scheduled_delivery_at,
    a.storage_bucket,
    a.storage_path,
    a.mime_type,
    u.story_text
  FROM updated u
  JOIN public.subscribers s ON s.id = u.subscriber_id
  JOIN public.story_audio a ON a.story_job_id = u.id;
$$;

CREATE OR REPLACE FUNCTION public.mark_story_delivery_sent(
  p_story_job_id UUID,
  p_provider_message_id TEXT DEFAULT NULL
)
RETURNS VOID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  target_email TEXT;
BEGIN
  SELECT s.parent_email
    INTO target_email
  FROM public.story_jobs j
  JOIN public.subscribers s ON s.id = j.subscriber_id
  WHERE j.id = p_story_job_id;

  UPDATE public.story_jobs
  SET
    status = 'sent',
    sent_at = now(),
    updated_at = now(),
    error_message = NULL
  WHERE id = p_story_job_id;

  INSERT INTO public.delivery_attempts (
    story_job_id,
    parent_email,
    status,
    provider_message_id
  )
  VALUES (
    p_story_job_id,
    target_email,
    'sent',
    p_provider_message_id
  );
END;
$$;

CREATE OR REPLACE FUNCTION public.mark_story_delivery_failed(
  p_story_job_id UUID,
  p_error_message TEXT
)
RETURNS VOID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  target_email TEXT;
BEGIN
  SELECT s.parent_email
    INTO target_email
  FROM public.story_jobs j
  JOIN public.subscribers s ON s.id = j.subscriber_id
  WHERE j.id = p_story_job_id;

  UPDATE public.story_jobs
  SET
    status = 'delivery_failed',
    updated_at = now(),
    error_message = p_error_message
  WHERE id = p_story_job_id;

  INSERT INTO public.delivery_attempts (
    story_job_id,
    parent_email,
    status,
    error_message
  )
  VALUES (
    p_story_job_id,
    target_email,
    'failed',
    p_error_message
  );
END;
$$;

-- Enable Row Level Security (RLS) to secure your database
ALTER TABLE public.subscribers ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.children ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.story_jobs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.story_audio ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.delivery_attempts ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow anonymous signup inserts on subscribers" ON public.subscribers;
DROP POLICY IF EXISTS "Allow anonymous signup inserts on children" ON public.children;
DROP POLICY IF EXISTS "Allow public status selection on subscribers" ON public.subscribers;
DROP POLICY IF EXISTS "Allow public status selection on children" ON public.children;
DROP POLICY IF EXISTS "Allow updates for webhook confirmation on subscribers" ON public.subscribers;

-- The app server and n8n workflows use the Supabase service role key, which bypasses RLS.
-- Do not add public SELECT or UPDATE policies for these tables because they contain parent
-- emails, child details, payment status, and private storage paths.

REVOKE EXECUTE ON FUNCTION public.enqueue_tomorrow_story_jobs() FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.enqueue_signup_story_job(BIGINT, INTERVAL) FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.enqueue_signup_story_job_with_message(BIGINT, INTERVAL) FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.claim_ready_story_generations(INTEGER) FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.mark_story_generation_failed(UUID, TEXT, BOOLEAN) FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.claim_ready_story_deliveries(INTEGER) FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.mark_story_delivery_sent(UUID, TEXT) FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.mark_story_delivery_failed(UUID, TEXT) FROM PUBLIC, anon, authenticated;

GRANT EXECUTE ON FUNCTION public.enqueue_tomorrow_story_jobs() TO service_role;
GRANT EXECUTE ON FUNCTION public.enqueue_signup_story_job(BIGINT, INTERVAL) TO service_role;
GRANT EXECUTE ON FUNCTION public.enqueue_signup_story_job_with_message(BIGINT, INTERVAL) TO service_role;
GRANT EXECUTE ON FUNCTION public.claim_ready_story_generations(INTEGER) TO service_role;
GRANT EXECUTE ON FUNCTION public.mark_story_generation_failed(UUID, TEXT, BOOLEAN) TO service_role;
GRANT EXECUTE ON FUNCTION public.claim_ready_story_deliveries(INTEGER) TO service_role;
GRANT EXECUTE ON FUNCTION public.mark_story_delivery_sent(UUID, TEXT) TO service_role;
GRANT EXECUTE ON FUNCTION public.mark_story_delivery_failed(UUID, TEXT) TO service_role;
